version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build: .
    container_name: backend_container
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: blog
      DATABASE_NAME: blog_db  # Corrected the database name
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - backend_network
    command: npx nodemon server.mjs  # Add nodemon for the backend
    dns:
      - 8.8.8.8  # Google's public DNS
      - 8.8.4.4

networks:
  backend_network:

volumes:
  mysql_data:
