version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build: .
    container_name: backend_container
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: blog
      DATABASE_NAME: blog_bd
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  mysql_data:
